package com.ningbai.blog.model;

public class Blog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.id
     *
     * @mbg.generated Sat Mar 14 15:24:21 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.title
     *
     * @mbg.generated Sat Mar 14 15:24:21 CST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.content
     *
     * @mbg.generated Sat Mar 14 15:24:21 CST 2020
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.tags
     *
     * @mbg.generated Sat Mar 14 15:24:21 CST 2020
     */
    private String tags;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.gmt_create
     *
     * @mbg.generated Sat Mar 14 15:24:21 CST 2020
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.gmt_modify
     *
     * @mbg.generated Sat Mar 14 15:24:21 CST 2020
     */
    private Long gmtModify;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.view_count
     *
     * @mbg.generated Sat Mar 14 15:24:21 CST 2020
     */
    private Long viewCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.like_count
     *
     * @mbg.generated Sat Mar 14 15:24:21 CST 2020
     */
    private Long likeCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.author
     *
     * @mbg.generated Sat Mar 14 15:24:21 CST 2020
     */
    private String author;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.id
     *
     * @return the value of blog.id
     *
     * @mbg.generated Sat Mar 14 15:24:21 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.id
     *
     * @param id the value for blog.id
     *
     * @mbg.generated Sat Mar 14 15:24:21 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.title
     *
     * @return the value of blog.title
     *
     * @mbg.generated Sat Mar 14 15:24:21 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.title
     *
     * @param title the value for blog.title
     *
     * @mbg.generated Sat Mar 14 15:24:21 CST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.content
     *
     * @return the value of blog.content
     *
     * @mbg.generated Sat Mar 14 15:24:21 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.content
     *
     * @param content the value for blog.content
     *
     * @mbg.generated Sat Mar 14 15:24:21 CST 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.tags
     *
     * @return the value of blog.tags
     *
     * @mbg.generated Sat Mar 14 15:24:21 CST 2020
     */
    public String getTags() {
        return tags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.tags
     *
     * @param tags the value for blog.tags
     *
     * @mbg.generated Sat Mar 14 15:24:21 CST 2020
     */
    public void setTags(String tags) {
        this.tags = tags == null ? null : tags.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.gmt_create
     *
     * @return the value of blog.gmt_create
     *
     * @mbg.generated Sat Mar 14 15:24:21 CST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.gmt_create
     *
     * @param gmtCreate the value for blog.gmt_create
     *
     * @mbg.generated Sat Mar 14 15:24:21 CST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.gmt_modify
     *
     * @return the value of blog.gmt_modify
     *
     * @mbg.generated Sat Mar 14 15:24:21 CST 2020
     */
    public Long getGmtModify() {
        return gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.gmt_modify
     *
     * @param gmtModify the value for blog.gmt_modify
     *
     * @mbg.generated Sat Mar 14 15:24:21 CST 2020
     */
    public void setGmtModify(Long gmtModify) {
        this.gmtModify = gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.view_count
     *
     * @return the value of blog.view_count
     *
     * @mbg.generated Sat Mar 14 15:24:21 CST 2020
     */
    public Long getViewCount() {
        return viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.view_count
     *
     * @param viewCount the value for blog.view_count
     *
     * @mbg.generated Sat Mar 14 15:24:21 CST 2020
     */
    public void setViewCount(Long viewCount) {
        this.viewCount = viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.like_count
     *
     * @return the value of blog.like_count
     *
     * @mbg.generated Sat Mar 14 15:24:21 CST 2020
     */
    public Long getLikeCount() {
        return likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.like_count
     *
     * @param likeCount the value for blog.like_count
     *
     * @mbg.generated Sat Mar 14 15:24:21 CST 2020
     */
    public void setLikeCount(Long likeCount) {
        this.likeCount = likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.author
     *
     * @return the value of blog.author
     *
     * @mbg.generated Sat Mar 14 15:24:21 CST 2020
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.author
     *
     * @param author the value for blog.author
     *
     * @mbg.generated Sat Mar 14 15:24:21 CST 2020
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }
}