package com.ningbai.blog.model;

public class Record {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.id
     *
     * @mbg.generated Sat Mar 21 21:43:57 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.type
     *
     * @mbg.generated Sat Mar 21 21:43:57 CST 2020
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.creator
     *
     * @mbg.generated Sat Mar 21 21:43:57 CST 2020
     */
    private Long creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.receiver
     *
     * @mbg.generated Sat Mar 21 21:43:57 CST 2020
     */
    private Long receiver;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.receiver_type
     *
     * @mbg.generated Sat Mar 21 21:43:57 CST 2020
     */
    private Integer receiverType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.state
     *
     * @mbg.generated Sat Mar 21 21:43:57 CST 2020
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.gmt_create
     *
     * @mbg.generated Sat Mar 21 21:43:57 CST 2020
     */
    private Long gmtCreate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.id
     *
     * @return the value of record.id
     *
     * @mbg.generated Sat Mar 21 21:43:57 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.id
     *
     * @param id the value for record.id
     *
     * @mbg.generated Sat Mar 21 21:43:57 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.type
     *
     * @return the value of record.type
     *
     * @mbg.generated Sat Mar 21 21:43:57 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.type
     *
     * @param type the value for record.type
     *
     * @mbg.generated Sat Mar 21 21:43:57 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.creator
     *
     * @return the value of record.creator
     *
     * @mbg.generated Sat Mar 21 21:43:57 CST 2020
     */
    public Long getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.creator
     *
     * @param creator the value for record.creator
     *
     * @mbg.generated Sat Mar 21 21:43:57 CST 2020
     */
    public void setCreator(Long creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.receiver
     *
     * @return the value of record.receiver
     *
     * @mbg.generated Sat Mar 21 21:43:57 CST 2020
     */
    public Long getReceiver() {
        return receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.receiver
     *
     * @param receiver the value for record.receiver
     *
     * @mbg.generated Sat Mar 21 21:43:57 CST 2020
     */
    public void setReceiver(Long receiver) {
        this.receiver = receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.receiver_type
     *
     * @return the value of record.receiver_type
     *
     * @mbg.generated Sat Mar 21 21:43:57 CST 2020
     */
    public Integer getReceiverType() {
        return receiverType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.receiver_type
     *
     * @param receiverType the value for record.receiver_type
     *
     * @mbg.generated Sat Mar 21 21:43:57 CST 2020
     */
    public void setReceiverType(Integer receiverType) {
        this.receiverType = receiverType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.state
     *
     * @return the value of record.state
     *
     * @mbg.generated Sat Mar 21 21:43:57 CST 2020
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.state
     *
     * @param state the value for record.state
     *
     * @mbg.generated Sat Mar 21 21:43:57 CST 2020
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.gmt_create
     *
     * @return the value of record.gmt_create
     *
     * @mbg.generated Sat Mar 21 21:43:57 CST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.gmt_create
     *
     * @param gmtCreate the value for record.gmt_create
     *
     * @mbg.generated Sat Mar 21 21:43:57 CST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }
}